{% set name = "mprocs" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pvolok/mprocs/archive/v{{ version }}.tar.gz
  sha256: 13059e3f474b17b0d806b2b6a79c17dd9b817793a0a6442ffd43ddaacb1db60c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - make
    - python
  host:
    - libxcb  # [linux]

test:
  commands:
    - mprocs --help

about:
  home: https://github.com/pvolok/mprocs
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Run multiple commands in parallel
  dev_url: https://github.com/pvolok/mprocs

extra:
  recipe-maintainers:
    - danielnachun
