{% set name = "mprocs" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pvolok/mprocs/archive/v{{ version }}.tar.gz
  sha256: a058a2806319a0a1ab644158b741e9a54be28540c88d15d213b820b3f97a65da

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - make
    - python
  host:
    - libxcb  # [linux]

test:
  commands:
    - mprocs --help

about:
  home: https://github.com/pvolok/mprocs
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Run multiple commands in parallel
  dev_url: https://github.com/pvolok/mprocs

extra:
  recipe-maintainers:
    - danielnachun
