schema_version: 1

context:
  version: "0.9.0"

package:
  name: mprocs
  version: ${{ version }}

source:
  url: https://github.com/pvolok/mprocs/archive/v${{ version }}.tar.gz
  sha256: fda5d8db13540459ea1ed65524f50c6492f12e0f627cde522164c17d6d7b9ecb

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make
    - python >=${{ python_min }}
  host:
    - if: linux
      then: libxcb

tests:
  - script:
      - mprocs --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Run multiple commands in parallel
  homepage: https://github.com/pvolok/mprocs
  repository: https://github.com/pvolok/mprocs

extra:
  recipe-maintainers:
    - danielnachun
